package com.example.arundhati.bibloreview;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

public class SureActivity extends AppCompatActivity {

TextView ts;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sure);

        final TextView Display= findViewById(R.id.vartext);
        ts=findViewById(R.id.ts);
        Bundle bn=getIntent().getExtras();
        String text= bn.getString("key");
        Display.setText(String.valueOf(text));

        Button buttonscan = findViewById(R.id.btnscan);
        buttonscan.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {

                Intent activity1Intent = new Intent(getApplicationContext(), ImageActivity.class);
                startActivity(activity1Intent);
            }
        });

        Button buttonsearch = findViewById(R.id.btnsearch);
        buttonsearch.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                ts.setMovementMethod(new ScrollingMovementMethod());
                Display.setText("");
                Bundle bn=getIntent().getExtras();
                String text= bn.getString("key");
                String q=String.valueOf(text);
                if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nThe Fault In Our Stars\n")) {
                    Display.setText("Name: The Fault In Our Stars \n Author: John Green \n Rating: 3 \n ");
                    ts.setText("Review: The Fault in our stars isn't a bad book, but I wouldn't consider it perfect like many do. The terminally sick characters rather enjoy their life and their daily routine rather than being grim and depressed about it, and it taught me to look at a new day as a gift. If you were to read the book, it's an easy read, and the protagonist gets into you. It feels oddly realistic, as though you are Hazel Grace. John Green has indeed written it beautifully. The ending was heart breaking and surprising, it was a real sharp turn of events, and it filled my heart with warmth. If I were to shed some tears on the story (cuz many do), I would probably do it in the last few chapters. The last 5 were so thoughtful and hit a soft spot in me.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nA Tap On The Window\n")){
                    Display.setText("Name: A Tap On The Window \n Author: Linwood Barclay \n Rating: 4.5 \n ");
                    ts.setText("Sometimes, doing the right thing is not always worth doing. It’s hard to be right all the time. It’s not an easy way to live your life.”\\r\\nA Tap on the Window by Linwood Barclay is a slow start, but five hundred odd pages later, when it all ends, it bounds to keep one on the edge.\\r\\nMost of us know what one bad decision can do, sometimes it can even change one’s side in a controversy. Our protagonist, Cal Weaver made one small decision around which the entire book revolves around.\\r\\nA desperate guy with his son dead, marriage in crumbles finds a young hottie tapping on his car window outside a bar, the perfect mystery case needed to spin a yarn. Surprisingly, Cal here was an ex-cop and is a Private Investigator, which makes him look pretty dumb to have made that decision, but he makes smarter ones in the future (though only in the end). The antagonist\\'s character kind of let me down and I wish it could have been darker there (Well, I’m a sucker for anything Dark).\\r\\nThe story ends with a wonderful twist where you see the perp(s) dealt with but the twist is one that you do not see coming and finally answers the questions that he has been posing throughout the book. To know what this is, go check out the book!");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nA Thousand Splendid Suns\n")){
                    Display.setText("Name: A Thousand Splendid Suns \n Author: Khaled Hosseini \n Rating: 4 \n ");
                    ts.setText("384 pages of emotional turmoil”\\r\\nThrough Riverbed publications, Hosseini pumps out yet another emotional rollercoaster that’s bound to move even the most cold hearted of men. The stand-alone second instalment set in the same setting of Taliban ruled state of Afghanistan, this piece of work enthralls you with its special way with words.\\r\\nFollowing the story of two women, Mariam and Laila, down trodden by the man’s cruel world, Hosseini spins a fantastic tale of courage, friendship and sacrifice set in such a place where the status of women is no better than animals. Two unrelated women develop the inextricable bond of a mother and daughter as they plough their way through the world in metaphorical shackles with their nigh inexorable spirits.\\r\\nThis story has all the emotions, happy notes of pre-Taliban era and the contrasting latter grim tone. It will move you, encourage you and solidify your respect towards women and what they go through. Definitely worth your time, as it adds something meaningful to your experience.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nSongs Of The Humpback Whale\n")){
                    Display.setText("Name: Songs Of The Humpback Whale \n Author: Jodi Picoult \n Rating: 4 \n ");
                    ts.setText("'Sometimes finding your own voice is a matter of listening to the heart...'.\\r\\nJane Jones has lived in the shadow of her renowned husband, Oliver Jones for years. The two has a rocky relationship and struggles to keep their love strong and the forgiveness intact but to no avail. Oliver is devoted to his career and as a result, he spends less time with his wife and his teenage daughter Rebecca, with whom he neglects to spend quality time with. After a heated altercation, Jane leaves with her daughter and with the help of her affectionate brother Joley, she is guided to his Massachusetts apple farm. She discovers her true calling and develops feelings for a handsome younger man, named Sam. Rebecca who is seeking to find solace becomes interested in a guy name Hadley, that is ten years older than her. As an expert at tracking humpback whales across oceans, Oliver searches for his wife and tries to repair a broken relationship. While on his journey, he sees things in a different light: The world, his family, and himself through his wife's eyes. Emotionally charged, griping, dramatic and poignant novel about the true meaning of love and security!");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nThe Fourth K\n")){
                    Display.setText("Name: The Fourth K \n Author: Mario Puzo \n Rating: 3.5 \n ");
                    ts.setText("This book is nowhere near as good as The Godfather, but it is the epitome of Puzo. He may be famous for dealing with Italian Americans/mafia/etc, but those are just familiar backdrops for him to use while he writes about power and manipulation. This is the ultimate story of power. You think Michael Corleone knew how to get things done, just wait until the POTUS gets fed up with terrorists (due largely to an accumulation of tragedy in his life) and decides to go all 'murica on everyone's ass.\\r\\nThis book is awesome. Casually starts out with the assassination of the Pope and only gets crazier from there. Puzo throws in kidnapping the president's daughter, hiding an atomic bomb in NYC, destroying middle eastern oil-producing cities/countries, and the US teetering on the edge of becoming a dictatorship. The story follows the white house, congress, and a group of the most powerful men in America while they do everything in their power to accomplish what they think is best for the country");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nSon of Neptune\n")){
                    Display.setText("Name: Son of Neptune \n Author: Rick Riordan \n Rating: 5 \n ");
                    ts.setText("“Life is only precious because it ends, kid.”//r//nOne cursed demigod, two new heroes, a quest to unleash the god of death.\\r\\nI have never been so happy to see a character to return than I have with Percy Jackson. I'm so glad that he made an appearance in this book, I felt like I missed all the characters from the Percy Jackson series, and its like reuniting with an old friend once again!\\r\\nSon of Neptune is the second book in the Heroes of Olympus series by Rick Riordan. This book follows Percy, Frank, and Hazel on an adventure to the land beyond the Gods. They face new monsters and battles more fierce than before and are issued a challenge that has a serious time crunch. Percy is unsure of his past since his memory seemed to have been wiped clean. Hazel came back to life in another person’s body and isn’t sure of the reason at all. Frank has always been chastised by his grandmother and when he learns he is a descendant of one of the greatest Gods on earth, he is amazed and the most uncertain he’s ever been. Frank even discovers he has magic powers and learns to use them wisely. The three of them have to work together to beat the new monsters and demons and beat time.\\r\\nI rooted for all the characters and I felt the pain of their decisions. I love how the characters trust each other and that they love each other so much that even when the bad guys try to turn them against each other, they talk it out between themselves. They are supportive and understanding to each other, instead of being a victim of betrayal and miscommunication and, ofcourse distrust, when usually teenage drama is surrounded by it. I love the counterpoint of Greek and Roman in this. I love how we get to see the two different lifestyles. I love that neither is held above the other. Indeed a great work by the Author.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nThanks For The Memories\n")){
                    Display.setText("Name: Thanks For The Memories \n Author: Cecelia Ahern \n Rating: 4 \n ");
                    ts.setText("After a horrible accident, Joyce Conway is trying to put her life back together. Her life and her marriage are in pieces, but Joyce tries to get back to living a normal life, despite advice from others. But something is stopping her.\\r\\nShe keeps having dreams of a beautiful blond haired girl, of places she has never been. She knows things that she shouldn’t about art, about architecture. She sees a beautiful woman in her dreams.\\r\\nJoyce sees and knows things she should not know. And it all started after her accident. Wanting to get to the bottom of things, to discover the reason for her newfound knowledge, Joyce tracks down her blood donor…Justin Hitchcock is a lonely man.\\r\\nHe hasn’t dated since his marriage broke up. Instead, he contends himself with touring universities, talking about art, about the only thing he has a passion for in life. He knows he’s lonely, knows that he needs to heal. What he doesn’t know is that his life is about to change\\r\\nI really enjoyed this book because I loved the whole idea and concept that Ahern came up with. I also enjoyed the romance between them even though they only speak two or three times in the book. I can imagine them marrying and everything, Ahern gives you enough just to let you imagine what happens next. My favourite part of this books concoction of good points was the humour. I loved the whole excursion to London with her father. Her crazy, funny ,and sweet father is what made this novel colourful for me. He added the extra dimension.\\r\\nOn the other hand it would have been nicer if the book had more time of the two main characters together. It felt almost unfinished. There were lots of circles in the plot. I was quite confused at the beginning as to what had happened to Joyce, I thought she had been in a car accident and I think that it would have worked without her having a miscarriage.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nAnd Then There Were None\n")){
                    Display.setText("Name: And Then There Were None \n Author: Agatha Christie \n Rating: 5 \n ");
                    ts.setText("“We shall none of us leave this island.”\\r\\nAnd then there were none, A beautifully penned book by Agatha Christie.\\r\\nA group of people are all individually invited to an island for a summer holiday in Devon. None of them 100% sure who their mysterious host is. Things become even more peculiar when their host isn’t there when they arrive, and doesn’t show themselves at all.\\r\\nOne by one the guests are killed, picked off, leaving the others terrified and paranoid. It was a fantastic mystery throughout. As tension becomes hysteria, the guests wonder who will be next, who is responsible for these murders, and why? A fantastic read that leaves you guessing until the very end");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nRed White and Royal Blue\n")){
                    Display.setText("Name: Red, White and Royal Blue \n Author:Casey McQuiston \n Rating: 4.5 \n ");
                    ts.setText("Red, White, and Royal Blue is indeed a roller coaster ride. It brought me up to the very top clouds of happiness only to then plummet me down to stressful situations but then brought me up again to happiness until it again brought tears to my eyes.\\r\\nThis book basically tells the story of two young men who fell in love. Something that should have been common and basic except that one of them is the son of the first female president of the United States and the other one is the Prince of England. Sentence - Orange - Being the two of the most important personalities in the world of developed nations, prevented them from exploring their romance and sexuality publicly. So far, I have never read about a main character questioning their sexuality in their 20s, which is so similar to the situations of many ,who are still discovering who they are. Each character is planned out so well and has personalities and traits that make them so pure and rich that you can immediately tell who said what or is doing what. Aside from this representation, this book has a lot of seemingly effortless diversity. It basically shows the political climate you can only wish was reality, which makes it a hopeful read. And it's a hilarious read as well. Overall, this book had me laughing and crying and loving these characters so much. I just realized that it sounds like I am fangirling BIG time, but who am I kidding? .");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n The Kill Club\n")){
                    Display.setText("Name: The Kill Club \n Author: Wendy Heard \n Rating: 4 \n ");
                    ts.setText("'First rule of murder club, don't talk about murder club.' As you may have guessed simply from the title The Kill Club by Wendy Heard is not a new or overly original plot but one that tackles the idea of the characters killing a stranger for another person to kill the horrible person in their life. Regardless of this idea being done before Wendy Heard still made a compelling story with her version.\\r\\nRandom murders are happening all over the city. People are terrified to leave the house, as people are being killed off in very public places. There is a serial killer on the loose that leaves his calling card...a playing card at the scene of the crime. Every victim is killed by an injection of poison that brings them to a painful death. The detectives are stumped because the killer seems to get a bit sloppy at times and sometimes he is 'dead on' perfect in his techniques.\\r\\nThe Kill Club had a nice fast pace to it as you learned of the characters and their situations and the action begins. The story also had plenty of twists and turns added into the mix that kept the pages turning once the characters begin to learn about the club and all that it offered. Despite the lack of originality with the plot this was still quite the solid read overall.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\nBlack Flamingo\n")){
                    Display.setText("Name: Black Flamingo\n Author: Dean Atta\n Rating: 5 \n ");
                    ts.setText("'I masquerade in makeup and feathers and I am applauded.'\\r\\nThe Black Flamingo is a novel written in verse. My first read ever in such a writing style; it did get me a little concerned. This story follows Michael, a mixed race, gay boy growing up in the UK. He is a part-Greek Cypriot and part-Jamaican ( If you want me to repeat, He’s a Half-Greek, though a Cypriot, living in London [I’m already jumping] ).\\r\\nThe narrative follows him from the very beginning of his life, up through his time at University; although the bulk of it does take place during his teen years.He goes in depth into his thoughts and feelings surrounding his family, his heritage, his heartache over his absentee father, his discovery of his sexuality and many other topical issues.\\r\\nWhen he joins the Drag Society he begins to gain the confidence he needs to finally be the person he wants to be. These sections, particularly the final scene with his performance, were incredibly moving and also inspiring. As a reader, it completely sucks you in. The book hardly gave me an opportunity to put it down, and this is why it is a MUST READ.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n There's no place like here\n")){
                    Display.setText("Name:There's No Place Like Here\n Author:Cecelia Ahern\n Rating: 4\n ");
                    ts.setText("'I can assume that there's only one thing more frustrating than not being able to find someone, and that's not being found. I would want someone to find me, more than anything .'\\r\\nIt all started when the childhood friend of Sandy Shortt went missing. The obsession for the things that got lost started from there. She wanted to know where those things went. Finding what is lost became her single goal. "The more people who love you, the more people you have out there to lose memories of you!" she said justifying the reason for distancing herself from other people. These are some phrases that readers could relate to. Sandy Shortt had many questions for which no one had answers. She joined Gardìa( Police force of Ireland)  hoping that she could find the things and people went missing. The different plots of the story which together gave a sense of suspense thriller was when Sandy herself went missing. Jack was hoping to find her. Sandy's present compelled Jack's journey of finding her and the story of Sandy's childhood fueled it further. Jack's instinct told him that finding Sandy will lead him to the way his brother is. She found all the answers to her questions right there when she found her childhood friend. Sandy got lost and found answers to all the questions she had. Ultimately, she got all the answers and so did Jack! This book doesn't diverge into many stories,rather it keeps the protagonist in the center! Reading this piece gives the reader a sense of fairytale. The urge to find answers led to Sandy finding answers all by herself. There's a place for everything that disappears. There's a place for everything that exists in this world. Something that goes missing is found someplace else. Yes, there is no place like here! Where the missing things get found.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n The Guest List \n")){
                    Display.setText("Name: The Guest List \n Author: Lucy Foley\n Rating: 5\n ");
                    ts.setText("A secluded mysterious island, with a restored Folly, a wedding planner, a self made publisher of an online magazine, a survival reality show star, close friends and family and a storm that's starting, the perfect combination to a thriller. Every guest comes with baggage and secrets, making this wedding celebration, a very special one. As the wedding festivities commence, past resentments and jealousies begin to co-mingle with the current reminiscences and well wishes. Everyone seems to have a motive to kill, or to be killed. Dangerous drinking games, ruining wedding clothes, an affair, rather multiple and the apparent perfect life of the bride, you name it and its there. Sprinkled in between these alternating character narratives, the reader is given a glimpse into the wedding night where hints are dropped regarding a murder. The pair duly marry but a storm raged outside and inside The Folly, where the wedding took place, a waitress screams, the lights go out, a few of the guests stumble drunkenly outside to work out what’s happening. There’s the danger of the cliff edge and peat bogs to swallow you up.\\r\\nIs someone dead?\\r\\nWho?\\r\\nWhat unravels is very atmospheric and tense and towards the end you find you are holding your breadth as you could cut the atmosphere with a knife. Literally. The island has a ghostly feel and has legends which adds an extra dimension and there are some really creepy scenes to match the folklore, not least around the screeching cormorants which are seen as harbingers of death and evil which adds another layer of tension. The book has everything fans of this genre like - tension, revenge, secrets, lies, cowardice, grief, cruelty, the list goes on making this the guest list from Hades. Caution : This is not a book for those who get triggered easily.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n The Picture of Dorian Grey\n")){
                    Display.setText("Name: The Picture of Dorian Grey\n Author: Oscar Wilde\n Rating: 4\n ");
                    ts.setText("Have you ever wondered what would happen if every evil deed you commit is reflected on your face?\\r\\nThe Picture of Dorian Gray is a classic masterpiece penned by the Irish genius and a very controversial author of his times, Oscar Wilde. The novel gives the reader a valuable and critical insight into the British society of the 19th century.\\r\\nBut the main focus are the 3 protagonists, Basil, Harry and Dorian himself, who each show a different perspective to life. We get to explore how Harry carefully influences Dorian with his own hedonistic views to life, and also how various elements and people of society affect him. The book delves into how the soul of a man can easily be impugned and to what ends one is ready to go to achieve one’s desires. Dorian is a beautiful masterpiece, a true piece of art, but is tarnished and stained as the story progresses. The depth of each scene is critical, every setting adds more and more flavour to the life of Dorian.\\r\\nOverall, the author displays the story for each reader to read and interpret as they wish to. The dialogues, especially those by Henry, truly prove to be memorable ones and set the tone of the book. A definite read for the young audience and a look into the true self of a person, this novel deserves all the praise it gets and more.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n 1984\n")){
                    Display.setText("Name: 1984\n Author: George Orwell\n Rating: 5\n ");
                    ts.setText("What book to pick up in these times than George Orwell’s last book that was published a year prior to his death. 1984 is regarded as not only the greatest dystopian novel but also the finest work produced by the author in his lifetime. To say that Orwell is a good writer would be a huge understatement. Everything from the characters to the setup to the story arch is intricately crafted to lock in together flawlessly, resulting in a 300-page sculpture chiseled by ink. You cannot help but connect with Winston, our protagonist as he like us is stuck in a world divided into parts that engage in endless warfare at the cost of its citizens. The premise of the book has been used by politicians and activists since time immemorial but it is truer now than ever. Propaganda and suppression are accepted as a part of regular life and the government has broken the illusion of control. To oppose them would certainly mean death, but your life is not the only thing that they’ll take away. The human body is obviously precious, but the soul is without a doubt the most valuable possession of a human being. Only after reading the book will you realize the dogma meticulously blended in our society that has been carried forward by generation after generation. 1984 is a literature masterpiece not only because it surrealistically represents our past and the future, but because it may be the only novel ever written that has you clutched in its story till the very last word.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n The Help\n")){
                    Display.setText("Name: The Help \n Author: Kathryn Scockett\n Rating:3.5\n ");
                    ts.setText("A contemporary to Gone With The Wind’\\r\\nNow a motion picture starring Emma Stone (which I haven’t seen) is a book that would have you think it has been written by a veteran author with years of writing experience behind her given the light yet dense palate the book serves you with. But ‘The Help’ in fact is Katheryn Stockett’s first novel which is a fact if you keep in mind while reading will make the process and appreciation for the author even sweeter.\\r\\nThe book has 3 POV’s- the benevolent Aibileen, the sassy Minny Jackson, and the white woman, Skeeter. The progression of the story is sometimes slow where you keep wondering whether the book needed to be 400 pages long, but the payoff is worth it. Unlike ‘Gone With The Wind’, ‘The Help’ hits you with a ground reality about the southern United States in the 1950s, before any real racial struggle in the south, set in a town where racists are termed as respected members of the society, and psychopaths as racists.\\r\\nJust like the multiple stories in the book itself, The Help is surprisingly funny, petrifying, and real. The mistakes of a novice author always include fussing up the ending or having a general gloomy tone when it comes to serious social issues, but Katheryn Stockett has made none. For an Indian engineering kid who likes to roam around in worlds and not the actual world, ‘The Help’ was a perfect companion that I carried with me everywhere in quarantine, from the bedroom to the living room and even to the bathroom. It’s evident that there’s a movie based on the book because the reading experience of ‘The Help’ is similar to watching a classic movie (but better): indulging characters, a comfortable yet intriguing environment, and a satisfying ending!");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n Divergent\n")){
                    Display.setText("Name: Divergent\n Author: Veronica Roth\n Rating: 4\n ");
                    ts.setText("The premise: Chicago of the future is a closed city-state. The citizenry really doesn't have any idea what is beyond their borders. They just know it's dangerous. Inside the city, humanity is divided into five factions based on moral imperatives. Candor, for instance, values truth above all else. They serve as lawyers and public speakers. Erudite values knowledge. They serve as teachers. Abnegation values self-denial and community service. They are the community's leaders, since they alone can be trusted not to be power-hungry.\\r\\nOur heroine Tris is born into Abnegation, but during her choosing ceremony at age sixteen, she decides to join the Dauntless, who value fearlessness and serve as the society's soldiers and guards. The novel follows her through her initiation training, during which Tris discovers that their society is not as harmonious as she once believed. Making things even worse, Tris must keep her true aptitude secret. She is in a small minority of people who are divergent -- whose skills could suit them for more than one faction. What this means is not at first clear, but it will make Tris's life very dangerous.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n Detention\n")){
                    Display.setText("Name: Detention\n Author: Riddhika Jain\n Rating: 4\n ");
                    ts.setText("'Tomorrow is always fresh, with no mistakes in it yet'\\r\\nDetention is the story of a studious seventeen years old Kayla Anderson who one day finds herself doing detentions for no particular reason with a teacher she hates. Slowly she starts liking the teacher and realises things about herself she didn't know earlier. One day Kayla discovers that she is not straight as she thought herself to be. The plot of the book is unique. It has themes of self identity, emotional turmoil, the need for social validation and love in all its forms. The pace of the book is fast, but at a point of time the book became monotonous for me because nothing much was happening. The narration didn't hold me much. The language on the other hand is very simple and understandable. Kudos to the author for portraying the emotions of the teenage years of ones life in its full colours. \\r\\nThere's drama, friendship, betrayal, love and a search for identity.\\r\\nThe character development of Kayla can be seen clearly, how she comes out after realising that she's in love with her teacher. The cover of the book is bold and beautiful and goes with the plot. All in all it was a good read and I would recommend this to people who are new to this genre of LGBTQ+ literature, and also who would like to know about the feelings of a person coming out.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n Six of Crows\n")){
                    Display.setText("Name: Six of crows\n Author:Leigh Bardugo\n Rating: 5\n ");
                    ts.setText("Six of Crows follows six teenagers living in the city of Ketterdam, a city of slums and crime lords.\\r\\nKaz Brekker, an infamous thief (also known as Dirtyhands) is promised a very large sum of money to kidnap Bo Yul-Bayur, a scientist from the Ice Court.\\r\\nThe Ice Court is the most highly protected place in Fjerda, and Kaz won't be able to gatecrash it alone. He needs a crew.\\r\\nHe recruits Inej Ghafa. Inej is known for her ability to climb buildings and move across impossible terrain with extreme agility. She's quiet but strong, and she's got quite an interesting background. Inej was kidnapped from her family's caravan and sold to a brothel in Ketterdam. When she eventually escaped, she entered into a contract with Per Haskell, a crime lord in Ketterdam. Inej's goal is to make enough money off of her work for Haskell to pay off her contract and return home to Ravka.\\r\\nNext, Kaz recruits Jesper Fahey. He is the crew's sharpshooter. Jesper is a lighthearted and sarcastic character, who enjoys gambling a bit more than he should.\\r\\nNina is the only trained Grisha in the crew. She is stuck in Ketterdam and is unable to go home. Nina is really confident and unapologetic about who she is. She's also loyal to her friends.\\r\\nMatthias a former Druskelle, soldiers from Fjerda. He has a history with Nina as the two of them helped each other after a storm destroyed their ship, with the two of them developing a trust. Nina betrays him which causes him to hate her, but he also loves her.\\r\\nWylan is the son of a merchant. He serves as the brains of the operation. Wylan is an intelligent engineer and inventor. He's very shy and awkward because he's been isolated for most of his life, but slowly warms to the other members of the crew.");
                }
                else if(q.equalsIgnoreCase("Are You Sure You Want To \nSearch For This Book?\n\n\n The Maze Runner \n")){
                    Display.setText("Name: The Maze Runner\n Author: James Dashner\n Rating: 5\n ");
                    ts.setText("The Maze Runner begins with Thomas finding himself memory-less, surrounded by teenage boys of varying ages, in a strange place called the Glade. Thomas immediately begins asking questions, attempting to get his bearings, though answers aren’t forth coming, and the Gladers are none to helpful. Nonetheless, life doesn’t seem too shabby in the Glade. There is a homestead, crops, barns filled with livestock, the sun always shines, and various supplies appear in “the box” each week upon request. There even appears to be order within the Glade, though it is filled with nothing but testosterone fueled teenage boys. There appears to be only a handful of rules, 1. Never threaten your fellow Gladers, 2. Everyone must pull their weight, 3. No one is allowed in the Maze aside from runners, 4. No one is allowed in the Maze after dark. Though the rules are rather self-explanatory, their necessity becomes all  too clear once Thomas is allowed to know what lurks behind the stone walls protecting the Glade. While no one knows how they came to arrive in the Glade, why they were sent, or who sent them, they all strive towards a common goal, solving the Maze and leaving the Glade. But once the first ever girl arrives into the Glade, a trigger is pulled, and the stakes for survival are raised.");
                }
            }
        });
    }
}